---
sudo: false
language: ruby
#cache:
#  bundler: true
rvm:
  - 2.4.1
#  - 2.4
#  - 2.5

gemfile:
  - gemfiles/virtual_attributes_50.gemfile


before_script:
  - sh -c "if [ '$DB' = 'pg' ]; then travis_setup_postgresql ; psql -c 'DROP DATABASE IF EXISTS virtual_attributes; CREATE DATABASE virtual_attributes;'; fi"
  - sh -c "if [ '$DB' = 'mysql2' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS virtual_attributes;'; fi"

env:
  - DB=sqlite3
  - DB=pg
