---
sudo: false
language: ruby
#cache:
#  bundler: true
rvm:
  - 2.4.1
#  - 2.4
#  - 2.5

services:
  - postgresql
#  - mysql
#addons:
#  postgresql: '9.5'

gemfile:
  - gemfiles/virtual_attributes_50.gemfile
#  - gemfiles/virtual_attributes_51.gemfile
#  - gemfiles/virtual_attributes_52.gemfile

before_install:
  # ruby 2.5
#  - gem update --system
#  - gem install bundler
  # ruby 2.5, rails 4.2:
#  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
#  - gem install bundler -v '< 2'

before_script:
  - sh -c "if [ '$DB' = 'pg' ]; then psql -c 'DROP DATABASE IF EXISTS virtual_attributes;' -U pg; fi"
  - sh -c "if [ '$DB' = 'pg' ]; then psql -c 'CREATE DATABASE virtual_attributes;' -U pg; fi"
  - sh -c "if [ '$DB' = 'mysql2' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS virtual_attributes;'; fi"

env:
  - DB=sqlite3
  - DB=pg
#  - DB=mysql2
